import cron from 'node-cron';
import Audio from '../models/audio';
import AutoGeneratedPlaylist from '../models/autoGeneratedPlaylist';

const generatePlaylist = async () => {
  const result = await Audio.aggregate([
    { $sort: { likes: -1 } },
    {
      $group: {
        _id: '$category',
        audios: { $push: '$$ROOT._id' },
      },
    },
    { $limit: 20 },
  ]);

  result.map(async (item) => {
    await AutoGeneratedPlaylist.updateOne(
      { title: item._id },
      { $set: { items: item.audios } },
      { upsert: true }
    );
  });
};

cron.schedule('0 0 * * *', async () => {
  await generatePlaylist();
});
